spring:
  application:
    name: music-mv-server
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
server:
  port: 8080
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
  servlet:
    context-path: /music
logging:
  config: classpath:logback-config.xml
  file: logs/music-starchild.log

# 自定义数据库
datasource:
  driverClassName: com.mysql.jdbc.Driver
  connectionTimeout: 60000
  idleTimeout: 10000
  maxLifetime: 60000
  maximumPoolSize: 10
  minIdle: 5
  url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false
  username: root
  password: root